// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBq6MxcLFPaWFZaCguGJqEnn_YfAAkrk',
    appId: '1:638916685013:web:af818a903e1ee2b589465c',
    messagingSenderId: '638916685013',
    projectId: 'somno-1c861',
    authDomain: 'somno-1c861.firebaseapp.com',
    storageBucket: 'somno-1c861.firebasestorage.app',
    measurementId: 'G-NYRJF56DQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQXSeQuEaU82akiq_-nDwHBfysobNRb0',
    appId: '1:638916685013:android:650a883a5b31706089465c',
    messagingSenderId: '638916685013',
    projectId: 'somno-1c861',
    storageBucket: 'somno-1c861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMvYtqTliOv6zP7TW3TaeEDgOkSRdGutU',
    appId: '1:638916685013:ios:75c95ae19c855f7889465c',
    messagingSenderId: '638916685013',
    projectId: 'somno-1c861',
    storageBucket: 'somno-1c861.firebasestorage.app',
    iosBundleId: 'com.example.somno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMvYtqTliOv6zP7TW3TaeEDgOkSRdGutU',
    appId: '1:638916685013:ios:75c95ae19c855f7889465c',
    messagingSenderId: '638916685013',
    projectId: 'somno-1c861',
    storageBucket: 'somno-1c861.firebasestorage.app',
    iosBundleId: 'com.example.somno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBq6MxcLFPaWFZaCguGJqEnn_YfAAkrk',
    appId: '1:638916685013:web:f1d9ff2ef5d8502789465c',
    messagingSenderId: '638916685013',
    projectId: 'somno-1c861',
    authDomain: 'somno-1c861.firebaseapp.com',
    storageBucket: 'somno-1c861.firebasestorage.app',
    measurementId: 'G-E6PKD0LX3H',
  );
}
